### PR TITLE
Add temperature

### LINKED ISSUE #30: As form teacher, I would want to record the temperature of each of my students, especially during this Coronavirius epidemic,
to keep track of the health of my students.

### LINKED ISSUE #44: Basic Implementation of Class Administration feature

### PR DESCRIPTION
**Pull request by Yuanyu97**
Added temperature attribute to Student.

### CODE REVIEW

**Review by jerrenss — COMMENTED** [review]
You are making temperature is a new attribute of Student right? Are we intending to store more than one temperature? Since initially we had discussed to have weekly display of information.

Other than that I think the code is well written!

**Review by gsyndromes — COMMENTED** [review]
can consider modifying the storage such that it will track all temperature allocated to the student! cause it looks like this will be an attribute of the student that is only able to track its current temperature.

alternatively, we can modifying our requireents such that the form teacher can consider tracking daily attributes of the student

**Comment by Yuanyu97** [comment]
> You are making temperature is a new attribute of Student right? Are we intending to store more than one temperature? Since initially we had discussed to have weekly display of information.
> 
> Other than that I think the code is well written!

Yes indeed! I think what we can do it to create a list of students with the same attributes, but setting the temperature and attendance to null for every new day, then the teacher can just set the temperatures and attendance accordingly every day since that is what a teacher does. The weekly display of temperatures or attendance I have not thought much of it yet, but I think this could work. What do you think? Thank you for your kind words!

**Comment by Yuanyu97** [comment]
> can consider modifying the storage such that it will track all temperature allocated to the student! cause it looks like this will be an attribute of the student that is only able to track its current temperature.
> 
> alternatively, we can modifying our requireents such that the form teacher can consider tracking daily attributes of the student

Yes, I agree! I have not yet modified the storage to keep track of the weekly details of the students, but only the daily version. I will keep that in mind!

Yes, I agree with the alternative too! That was the idea I mentioned in @jerrenss comment. I think we can make some of the attributes such as name, email etc static, and set the temperature and attendance to null every new day so that the teacher can update those information accordingly. What do you think?

**Comment by gsyndromes** [comment]
> > can consider modifying the storage such that it will track all temperature allocated to the student! cause it looks like this will be an attribute of the student that is only able to track its current temperature.
> > alternatively, we can modifying our requireents such that the form teacher can consider tracking daily attributes of the student
> 
> Yes, I agree! I have not yet modified the storage to keep track of the weekly details of the students, but only the daily version. I will keep that in mind!
> 
> Yes, I agree with the alternative too! That was the idea I mentioned in @jerrenss comment. I think we can make some of the attributes such as name, email etc static, and set the temperature and attendance to null every new day so that the teacher can update those information accordingly. What do you think?

Great idea! This idea sounds good to me!

**Comment by TheElectricBlender** [comment]
Looks good to merge! Good job circle fish!

**Pull request merged**
